import Link from "next/link";
import {
  Show,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import Hero from "@/components/landing/Hero";
import FeatureCard from "@/components/landing/FeatureCard";
import PricingCard from "@/components/landing/PricingCard";
import Button from "@/components/ui/Button";

const painPoints = [
  {
    icon: "🔍",
    title: "Scattered sources",
    description:
      "Tracking 50+ government sites, regulatory bodies, and legislative databases manually is unsustainable.",
  },
  {
    icon: "📄",
    title: "Information overload",
    description:
      "100+ pages of legal documents published weekly. Your team can't read everything and still ship product.",
  },
  {
    icon: "⏰",
    title: "Too late",
    description:
      "Finding out about compliance deadlines after they pass means costly retrofits and potential fines.",
  },
];

const steps = [
  {
    icon: "📡",
    title: "Monitor",
    description:
      "Track AI bills, guidance documents, and public consultations automatically from 15+ government sources.",
  },
  {
    icon: "🧠",
    title: "Understand",
    description:
      "AI-powered analysis tells you what changed, why it matters, and which products are affected.",
  },
  {
    icon: "🎯",
    title: "Act",
    description:
      "Generate impact memos, compliance timelines, and stakeholder briefs ready for your team.",
  },
];

const features = [
  {
    icon: "📋",
    title: "Daily briefings",
    description:
      "5-10 curated updates every morning, sorted by impact level and tailored to your product category.",
  },
  {
    icon: "📊",
    title: "Impact analysis",
    description:
      "For every update: what changed, why it matters, who's affected, and what to do next.",
  },
  {
    icon: "👁",
    title: "Watchlist alerts",
    description:
      "Track specific topics like EU AI Act or export controls. Get notified the moment something new drops.",
  },
  {
    icon: "📤",
    title: "Export tools",
    description:
      "Export briefings as Markdown or copy to clipboard. Share with your compliance team instantly.",
  },
];

const faqs = [
  {
    q: "What sources do you monitor?",
    a: "We track 15+ Tier-1 sources including the EU AI Office, NIST, FTC, European Parliament, OECD, and more. New sources are added regularly.",
  },
  {
    q: "How accurate are the AI summaries?",
    a: "Summaries are generated by Claude and reviewed against source material. Each briefing links directly to the original document so you can verify.",
  },
  {
    q: "Can I export the briefings?",
    a: "Yes. Every article and impact note can be exported as Markdown or copied to clipboard. PDF export is coming soon.",
  },
  {
    q: "What happens after the trial?",
    a: "After 14 days, you'll be charged $20/month. You can cancel anytime from your settings page. No questions asked.",
  },
  {
    q: "Do you cover state-level AI policy?",
    a: "Yes. We monitor key state-level AI bills from California, New York, and other active states, in addition to federal and EU policy.",
  },
  {
    q: "How often is data updated?",
    a: "Sources are checked multiple times per day. Most updates appear in your dashboard within hours of publication.",
  },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-white">
      <nav className="border-b border-gray-100">
        <div className="max-w-6xl mx-auto px-4 py-4 flex items-center justify-between">
          <span className="text-xl font-bold text-gray-900">GovSignal AI</span>
          <div className="flex items-center gap-4">
            <Link
              href="/pricing"
              className="text-sm text-gray-600 hover:text-gray-900 transition-colors"
            >
              Pricing
            </Link>

            <Show when="signed-out">
              <div className="flex items-center gap-4">
                <SignInButton>
                  <button
                    type="button"
                    className="text-sm text-gray-600 hover:text-gray-900 transition-colors"
                  >
                    Sign In
                  </button>
                </SignInButton>
                <SignUpButton>
                  <button
                    type="button"
                    className="inline-flex items-center justify-center rounded-lg bg-blue-600 px-3 py-1.5 text-sm font-medium text-white transition-colors hover:bg-blue-700"
                  >
                    Start Free Trial
                  </button>
                </SignUpButton>
              </div>
            </Show>

            <Show when="signed-in">
              <div className="flex items-center gap-4">
                <Link
                  href="/dashboard"
                  className="text-sm text-gray-600 hover:text-gray-900 transition-colors"
                >
                  Dashboard
                </Link>
                <UserButton />
              </div>
            </Show>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <Hero />

      {/* Problem */}
      <section className="py-20 px-4 bg-gray-50">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-gray-900 text-center">
            Why AI companies miss critical policy updates
          </h2>
          <div className="mt-12 grid md:grid-cols-3 gap-8">
            {painPoints.map((p) => (
              <FeatureCard key={p.title} {...p} />
            ))}
          </div>
        </div>
      </section>

      {/* Solution */}
      <section className="py-20 px-4">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-gray-900 text-center">
            Three steps to stay ahead
          </h2>
          <div className="mt-12 grid md:grid-cols-3 gap-8">
            {steps.map((s, i) => (
              <div key={s.title} className="text-center">
                <div className="inline-flex items-center justify-center w-12 h-12 rounded-full bg-blue-100 text-blue-600 font-bold text-lg mb-4">
                  {i + 1}
                </div>
                <h3 className="text-lg font-semibold text-gray-900">
                  {s.title}
                </h3>
                <p className="mt-2 text-sm text-gray-600 leading-relaxed">
                  {s.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-20 px-4 bg-gray-50">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-gray-900 text-center">
            Everything you need
          </h2>
          <div className="mt-12 grid md:grid-cols-2 gap-8">
            {features.map((f) => (
              <FeatureCard key={f.title} {...f} />
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section className="py-20 px-4">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-gray-900 text-center">
            Simple, transparent pricing
          </h2>
          <div className="mt-12">
            <PricingCard />
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-20 px-4 bg-gray-50">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-3xl font-bold text-gray-900 text-center mb-12">
            Frequently asked questions
          </h2>
          <div className="space-y-6">
            {faqs.map((faq) => (
              <div
                key={faq.q}
                className="rounded-lg border border-gray-200 bg-white p-6"
              >
                <h3 className="font-semibold text-gray-900">{faq.q}</h3>
                <p className="mt-2 text-sm text-gray-600 leading-relaxed">
                  {faq.a}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-20 px-4">
        <div className="max-w-2xl mx-auto text-center">
          <h2 className="text-3xl font-bold text-gray-900">
            Start monitoring AI policy today
          </h2>
          <div className="mt-8">
            <Button href="/sign-up" size="lg">
              Start Free Trial
            </Button>
          </div>
          <p className="mt-4 text-sm text-gray-500">
            No credit card required
          </p>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-gray-200 py-8 px-4">
        <div className="max-w-6xl mx-auto flex items-center justify-between text-sm text-gray-500">
          <span>GovSignal AI</span>
          <div className="flex gap-6">
            <Link href="/pricing" className="hover:text-gray-900 transition-colors">
              Pricing
            </Link>
            <Link href="/sign-in" className="hover:text-gray-900 transition-colors">
              Sign In
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
